// <auto-generated />
using System;
using Locadora.Aluguel.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Locadora.Aluguel.Migrations
{
    [DbContext(typeof(AluguelDbContext))]
    [Migration("20241123205812_configs")]
    partial class configs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Locadora.Aluguel.Models.Aluguel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .HasDefaultValueSql("'aluguel_' || abs(random() % 89999999 + 10000000)");

                    b.Property<string>("CodigoCliente")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cliente_id");

                    b.Property<string>("CodigoVeiculo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("veiculo_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime>("DataFinal")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_final");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_inicio");

                    b.Property<bool>("Inativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inativo");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("TEXT")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.ToTable("Aluguels");
                });
#pragma warning restore 612, 618
        }
    }
}
